name: Build and Store Artifacts for Anaveo

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Setup MSBuild for .NET Framework
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      # 3. Restore NuGet packages
      - name: Restore NuGet packages
        run: nuget restore Anaveo/Anaveo.sln

      # 4. Build the WPF project in Release mode
      - name: Build Anaveo WPF project
        run: msbuild Anaveo/Anaveo.sln /p:Configuration=Release

      # **(NEW)** Step สำหรับเซต DATE_TIME ใน env
      - name: Set DATE_TIME env
        # ใช้ PowerShell เพื่อให้ได้ฟอร์แมต YYYYMMDD-HHMMSS
        run: echo "DATE_TIME=$(Get-Date -Format 'yyyyMMdd-HHmmss')" >> $env:GITHUB_ENV
        shell: pwsh

      # 5. Upload build output as artifact
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Anaveo-Build-${{ env.DATE_TIME }}
          path: Anaveo/bin/Release
